# Generated by Django 3.1.1 on 2020-09-24 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('content', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('auther_mail', models.EmailField(default='', max_length=254)),
                ('type', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active')], max_length=30)),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
