# Generated by Django 3.1.1 on 2020-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0002_auto_20200924_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='guests',
            field=models.CharField(choices=[('adults', 'adults'), ('children', 'children'), ('infants', 'infants')], default=2, max_length=30),
            preserve_default=False,
        ),
    ]
